# Generated by Django 4.2.2 on 2023-07-08 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('phone', models.IntegerField()),
                ('status', models.CharField(choices=[('deliverd', 'delivered'), ('out for delivery', 'out for delivery'), ('cancel', 'cancel'), ('shipped', 'shipped'), ('order placed', 'order placed')], default='order placed', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('Books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
